#!/usr/bin/env bash

set -eu

config() {
	log "prepare configuration"
	gomplate --input-dir /etc/angie/templates --output-dir /etc/angie
}

log() {
	echo "$(basename $0): $@" >&2
}

main() {
	[ $# -eq 0 ] && set -- "${ANGIE_BINARY}" "-g" "daemon off;"

	[ "$ANGIE_FEATURE_TEMPLATE" = on ] && config
	[ "$ANGIE_FEATURE_RELOAD" = on ] || exec "$@"

	local pid rc

	trap 'log "got SIGHUP"; reload' SIGHUP
	trap 'log "got SIGQUIT"; quit'  SIGQUIT
	trap 'log "got SIGTERM"; stop'  SIGTERM

	"$@" &
	log "started '$@' pid:$!"

	while : ; do
		wait -n -p pid && rc=0 || rc=$?

		if [ -n "${pid:-}" ]; then
			log "process pid:$pid exited rc:$rc"
			exit $rc
		fi
	done
}

quit() {
	angie -s quit; wait
	log "exit"
	exit 0
}

reload() {
	[ "$ANGIE_FEATURE_TEMPLATE" = on ] && config
	angie -s reload
	log "reloaded"
}

stop() {
	angie -s stop; wait
	log "exit"
	exit 0
}

main "$@"
